# Basic math with python（パイソンで数学基礎）

numpyでvector・matrixの計算を練習しましょう

## 2.1 Vector

numpyをimportして計算の準備をします

In [1]:
import numpy as np

### 2.1.1 Make vectors  :     a [1,3,5,7,9],    b [2,4,6,8,10]

In [2]:
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [3]:
b = np.array([2,4,6,8,10])
b

array([ 2,  4,  6,  8, 10])

### 2.1.2 add vectors : a+b


In [4]:
a+b

array([ 3,  7, 11, 15, 19])

### 2.1.3 subtract vectors : b-a



In [5]:
b-a

array([1, 1, 1, 1, 1])

### 2.1.4 scalar multiplication 

In [6]:
a*3

array([ 3,  9, 15, 21, 27])

In [7]:
2*b

array([ 4,  8, 12, 16, 20])

In [8]:
(a+b)*3

array([ 9, 21, 33, 45, 57])

### 2.1.5 Devision by scalar  

In [9]:
b/2

array([1., 2., 3., 4., 5.])

### 2.1.6 Multiplication and division of vector and vector by elements 

elements (要素) ごとに掛け算・割り算を行います

In [11]:
a*b

array([ 2, 12, 30, 56, 90])

In [12]:
b/a

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111])

### 2.1.7 Multiplication of vector and vector 

inner product (内積)の計算です。2+12+30+56+90=190  となります。

In [31]:
a.dot(b)

190

### 2.1.8   Count numbers of elements in vector 


要素の数を数えます。

In [34]:
len(a)

5

In [35]:
len(b)

5

## 2.2 Matrices

### 2.2.1 Make matrices

In [37]:
A = np.array([1,3,2,4]).reshape(2,2)
A

array([[1, 3],
       [2, 4]])

In [39]:
B = np.array([2,5,9,4]).reshape(2,2)
B

array([[2, 5],
       [9, 4]])

In [40]:
C = np.array([1,3,5,4,10,8]).reshape(2,3) 
C

array([[ 1,  3,  5],
       [ 4, 10,  8]])

### 2.2.2 dimension of matrices (行列の次元）

In [41]:
A.shape

(2, 2)

In [42]:
B.shape

(2, 2)

In [43]:
C.shape

(2, 3)

For example matrix C has 2 rows and 3 columns　（２行３列の行列）

### 2.2.3 add matrices 

In [45]:
A+B

array([[ 3,  8],
       [11,  8]])

### 2.2.4 subtract matrices

In [47]:
B-A 

array([[1, 2],
       [7, 0]])

In [46]:
A-B

array([[-1, -2],
       [-7,  0]])

### 2.2.5 scalar multiplication of matrices



In [48]:
A*3

array([[ 3,  9],
       [ 6, 12]])

In [49]:
2*B

array([[ 4, 10],
       [18,  8]])

In [50]:
(A+B)*3

array([[ 9, 24],
       [33, 24]])

### 2.2.6 scalar devision of matrices 

In [52]:
A/3

array([[0.33333333, 1.        ],
       [0.66666667, 1.33333333]])

In [53]:
B/2

array([[1. , 2.5],
       [4.5, 2. ]])

### 2.2.7 Multiplication and devision of matrices by elements 

In [54]:
A*B

array([[ 2, 15],
       [18, 16]])

In [55]:
A/B

array([[0.5       , 0.6       ],
       [0.22222222, 1.        ]])

### 2.2.8 Multiply matrices and matrices 

In [56]:
A.dot(B)

array([[29, 17],
       [40, 26]])

In [57]:
B.dot(A)

array([[12, 26],
       [17, 43]])

Both results (A.dot(B) and B.dot(A)) are generally different each other　（行列の積では交換法則は成り立ちません）　

### 2.2.9 identity matrix  (単位行列）

In [63]:
i2=np.identity(2)
i2

array([[1., 0.],
       [0., 1.]])

In [64]:
i3=np.identity(3)
i3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
i4=np.identity(4)
i4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
A.dot(i2)

array([[1., 3.],
       [2., 4.]])

In [67]:
i2.dot(A)

array([[1., 3.],
       [2., 4.]])

Nothing is changed when identity matrix is multiplied (単位行列を掛けても結果は変わりません）

### 2.2.10 inverse matrix (逆行列）

In [73]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [75]:
A.dot(Ainv)

array([[1., 0.],
       [0., 1.]])

In [74]:
Ainv.dot(A)

array([[1., 0.],
       [0., 1.]])

The results should be "identity matrix" when inverse matrix is multiplied (ある行列にその逆行列を掛けると単位行列になります）









 








##  2.3  覚えておくと便利

In [16]:
np.arange( 1, 10, 1 )

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])